var GAME_LEVELS = [
  ["  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "  x                             x ",
   "  x                        |    x ",
   "  x                             x ",
   "  x                             x ",
   "  x     |                       x ",
   "  x    xxx                xxx   xx",
   "  x                    =         x",
   "  x              o              xx",
   "  x                             x ",
   "  x             xxx             x ",
   " xx            xxxxx            x ",
   " x=            x!x!x            x ",
   " xx             xxx             x ",
   "  x             x x             xx",
   "  x          =                   x",
   "  x                             xx",
   "  x     o                 o     x ",
   "  x                             x ",
   "  x                             x ",
   "  x  @           o              x ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                  "],
  ["  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "  x                                         x ",
   "  x                                         x ",
   "  x                                         x ",
   "  x                                         x ",
   "  x                                         x ",
   "  x                                    o    x ",
   "  x                              |   xxxx   x ",
   "  x      o                                  x ",
   "  x      xxx xxx              xxxxxx        xx",
   "  x         v          =                     x",
   " xx                    o                    xx",
   " x       =            xxx        =          x ",
   " xx                  xxxxx                  xx",
   "  x                 xxx!xxx                 x ",
   "  x  !!!            x!xxx!x            !!!  x ",
   "  x  !!!            xxxxxxx            !!!  x ",
   "  x  !x!             x x x             !x!  x ",
   "  xxxxx                                 xxxxxx",
   "  x                                =         x",
   "  x        o                      o         xx",
   "  x                                         x ",
   "  x                                         x ",
   "  x  @                 o                    x ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                              "],
  ["  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "  x                                                        x ",
   "  x                  xx                  xx                x ",
   "  x                                                        x ",
   "  x                                                        x ",
   "  x                                                        x ",
   "  x                   |                 o                  x ",
   "  x                                  xxxx                  x ",
   "  x      o                                |          o     x ",
   "  x      xxx xxxxx                                xxxx     x ",
   "  x         v          =                                   x ",
   " xx                           xxx                          x ",
   " x       =                  xxxxxxx      =                 x ",
   " xx                        xx!xxx!xx                       x ",
   "  x                       xxxxx!xxxxx                      x ",
   "  x                 xxx    xx!xxx!xx    xxx                x ",
   "  x       o                xxxxxxxxx               o       x ",
   "  x      =xxxx =            x x x x        =    xxxx =     x ",
   "  x                         x x x x            =           x ",
   "  x                                                        x ",
   "  x                                                        x ",
   "  x                           =                            x ",
   "  x                                                        x ",
   "  x  @  o              o              o              o     x ",
   "  xxxxxxxxxxxx    xxxxxxxxxxx    xxxxxxxxxxx    xxxxxxxxxxxx ",
   "                                                             ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                             "],
  //end of game, you win!
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
